version: '3'
services:
  backend:
    build: ./mirage-intake/backend
    volumes:
      - ./mirage-intake/backend:/app
    ports:
      - "8000:8000"
  frontend:
    build: ./mirage-intake/frontend
    volumes:
      - ./mirage-intake/frontend:/app
    ports:
      - "3000:5173"
    depends_on:
      - backend
